version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db_proyecto2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./db/registros.sql:/docker-entrypoint-initdb.d/registros.sql
      - ./db/vistas.sql:/docker-entrypoint-initdb.d/vistas.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: bck_proyecto2
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev

volumes:
  db_data: